# Generated by Django 3.1.4 on 2021-02-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_skills',
            fields=[
                ('user', models.CharField(default=100, max_length=30, primary_key=True, serialize=False)),
                ('user_skill', models.CharField(default='None', max_length=1000)),
            ],
        ),
    ]
