# Generated by Django 3.1.4 on 2021-03-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_user_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_skills',
            new_name='user_lacking_skills',
        ),
    ]
