# Generated by Django 3.1.4 on 2021-01-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0004_auto_20210122_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.TextField(default=100, max_length=100),
        ),
    ]
