# Generated by Django 3.1.4 on 2021-01-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0005_auto_20210122_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.TextField(default=100, max_length=30),
        ),
        migrations.AddField(
            model_name='manual_input',
            name='user',
            field=models.TextField(default=100, max_length=30),
        ),
        migrations.AddField(
            model_name='technical',
            name='user',
            field=models.TextField(default=100, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.TextField(default=100, max_length=30),
        ),
    ]
