# Generated by Django 3.1.4 on 2021-01-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0006_auto_20210122_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.CharField(default=100, max_length=30),
        ),
        migrations.AlterField(
            model_name='manual_input',
            name='user',
            field=models.CharField(default=100, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.CharField(default=100, max_length=30),
        ),
        migrations.AlterField(
            model_name='technical',
            name='user',
            field=models.CharField(default=100, max_length=30),
        ),
    ]
