# Generated by Django 3.1.4 on 2021-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0007_auto_20210122_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='holland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
                ('interest_type', models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=15)),
            ],
        ),
    ]
