# Generated by Django 3.1.4 on 2021-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0008_holland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holland',
            name='question',
            field=models.CharField(max_length=50),
        ),
    ]
