# Generated by Django 3.1.4 on 2021-01-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0009_auto_20210122_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='holland',
            name='choice_field',
            field=models.CharField(choices=[('disagree', ''), ('slightly disagree', ''), ('neutral', ''), ('slightly agree', ''), ('agree', '')], default='neutral', editable=False, max_length=20, null=True),
        ),
    ]
