# Generated by Django 3.1.4 on 2021-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0010_holland_choice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holland',
            name='choice_field',
            field=models.CharField(choices=[('disagree', ''), ('slightly disagree', ''), ('neutral', ''), ('slightly agree', ''), ('agree', '')], default='neutral', max_length=20, null=True),
        ),
    ]
