# Generated by Django 3.1.4 on 2021-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0011_auto_20210127_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holland',
            name='choice_field',
            field=models.CharField(choices=[('disagree', 'disagree'), ('slightly disagree', 'slightly disagree'), ('neutral', 'neutral'), ('slightly agree', ''), ('agree', 'slightly agree')], default='neutral', max_length=20, null=True),
        ),
    ]
