# Generated by Django 3.1.4 on 2021-01-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0013_auto_20210127_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holland',
            name='choice_field',
        ),
    ]
