# Generated by Django 3.1.4 on 2021-02-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0015_holland_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='achievement',
        ),
        migrations.DeleteModel(
            name='technical',
        ),
        migrations.AddField(
            model_name='manual_input',
            name='achievements',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='manual_input',
            name='technicals',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
