# Generated by Django 3.1.4 on 2021-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0017_technical_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical_list',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technical_list',
            name='technical',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
