# Generated by Django 3.1.4 on 2021-02-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0019_auto_20210212_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual_input',
            name='technicals',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
