# Generated by Django 3.1.4 on 2021-02-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0020_manual_input_technicals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holland_score',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manual_input',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='id',
        ),
        migrations.AlterField(
            model_name='holland_score',
            name='user',
            field=models.CharField(default=100, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manual_input',
            name='user',
            field=models.CharField(default=100, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.CharField(default=100, max_length=30, primary_key=True, serialize=False),
        ),
    ]
