# Generated by Django 3.1.4 on 2021-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0022_holland_interests_job_description_related_job_profile_technical_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Filtered_Job',
            fields=[
                ('user', models.CharField(default=100, max_length=30, primary_key=True, serialize=False)),
                ('filtered_list', models.CharField(default='None', max_length=1000)),
            ],
        ),
    ]
