# Generated by Django 3.1.4 on 2021-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0023_user_filtered_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual_input',
            name='achievements',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
