# Generated by Django 3.1.4 on 2021-03-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0025_final_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(default=100, max_length=300)),
                ('education', models.CharField(default=100, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(default=100, max_length=300)),
                ('Knowledge', models.CharField(default=100, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(default=100, max_length=300)),
                ('skills', models.CharField(default=100, max_length=4000)),
            ],
        ),
    ]
