# Generated by Django 3.1.4 on 2021-03-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0026_education_knowledge_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual_input',
            old_name='achievements',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='manual_input',
            name='employed',
        ),
        migrations.AlterField(
            model_name='manual_input',
            name='experience',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
